In [2]:
from utils.analyse_results import GraphsTraining, Results, load_all_pickles, plot_time_bands, plot_time_bands_median
import pandas as pd
import numpy as np
import pickle
from pathlib import Path
train_info = GraphsTraining()

### Load Pyomo results in
* the first script is iterating over 15 different seeds with the same set of data

In [7]:
def results_to_df(results: dict) -> pd.DataFrame:
    rows = []
    for (cfg, date, seed), vals in results.items():
        layer_sizes, penalty, tol = cfg  # cfg is the first tuple element
        r = vals.get("result", {})
        rows.append(
            {
                "layer_sizes": layer_sizes,
                "penalty": penalty,
                "tol": tol,
                "date": date,
                "seed": seed,
                "solver_time": r.get("solver_time"),
                "termination": getattr(r.get("termination_condition"), "value", r.get("termination_condition")),
                "message": r.get("message"),
                "times_elapsed": vals.get("times_elapsed"),
                "mse_odeint": vals.get("mse_odeint"),
                "mse_coll_ode": vals.get("mse_coll_ode"),
                "mse_odeint_test": vals.get("mse_odeint_test"),
                "mse_coll_ode_test": vals.get("mse_coll_ode_test"),
            }
        )
    return pd.DataFrame(rows)

In [14]:
results_pyomo = load_all_pickles("results/pyomo_network_size/pyomo_rl_2026-01-26_22-38-00", recursive=False)[0]
pyomo_df_seeds = results_to_df(results_pyomo)

results_pyomo = load_all_pickles("results/pyomo_network_size/pyomo_rl_2026-01-26_23-10-42", recursive=False)[0]
pyomo_df_dates = results_to_df(results_pyomo)

Loaded results/pyomo_network_size/pyomo_rl_2026-01-26_22-38-00/results_full.pkl

Loaded 1 files from results/pyomo_network_size/pyomo_rl_2026-01-26_22-38-00
Loaded results/pyomo_network_size/pyomo_rl_2026-01-26_23-10-42/results_full.pkl

Loaded 1 files from results/pyomo_network_size/pyomo_rl_2026-01-26_23-10-42

In [18]:
pyomo_df_seeds.head(1)

,layer_sizes,penalty,tol,date,seed,solver_time,termination,message,times_elapsed,mse_odeint,mse_coll_ode,mse_odeint_test,mse_coll_ode_test
0,"[7, 4, 1]",0.00001,0.000001,2015-01-15,2203719317,5.673489,optimal,Ipopt 3.14.19\x3a Optimal Solution Found,5.673489,0.014837,0.015588,0.177485,0.178288

In [16]:
pyomo_df_seeds.groupby("layer_sizes")[["times_elapsed","mse_coll_ode","mse_coll_ode_test"]].mean()

             times_elapsed  mse_coll_ode  mse_coll_ode_test
layer_sizes
[7, 128, 1]      48.628421      0.019632           0.151088
[7, 16, 1]        6.882207      0.026704           0.176181
[7, 32, 1]       11.930853      0.016799           0.166746
[7, 4, 1]         3.160783      0.074757           0.911308
[7, 64, 1]       26.076865      0.013454           0.142562
[7, 8, 1]         3.960035      0.071949           0.694285

In [17]:
pyomo_df_dates.groupby("layer_sizes")[["times_elapsed","mse_coll_ode","mse_coll_ode_test"]].mean()

             times_elapsed  mse_coll_ode  mse_coll_ode_test
layer_sizes
[7, 128, 1]      39.523298      0.230798           2.569817
[7, 16, 1]        6.120826      0.082831           0.690114
[7, 32, 1]        9.938667      0.052270           1.825717
[7, 4, 1]         3.432491      0.305992           0.628372
[7, 64, 1]       19.620832      0.135422           1.098205
[7, 8, 1]         3.855283      0.168406           1.406523