In [1]:
from utils.analyse_results import GraphsTraining, Results, load_all_pickles, plot_time_bands

train_info = GraphsTraining()

In [15]:
results_reg_norm = load_all_pickles("results/study_vdp/pyomo_network_size/pyomo_ho_32_180126", recursive=False)
results_reg_norm_df = Results.flatten_convergence_data(results_reg_norm, key_list=["system", "reg", "tol"], model_type="pyomo")

results_no_reg_norm = load_all_pickles("results/study_vdp/pyomo_network_size/pyomo_ho_32_190126", recursive=False)
results_no_reg_norm_df = Results.flatten_convergence_data(results_no_reg_norm, key_list=["system", "reg", "tol"], model_type="pyomo")

Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/1181949418_2026-01-18_20-26.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/1606738259_2026-01-18_20-06.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/1815805956_2026-01-18_20-23.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/2296125966_2026-01-18_19-44.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/2547568323_2026-01-18_20-02.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/2807268307_2026-01-18_19-54.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/2828764599_2026-01-18_20-09.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/3197297230_2026-01-18_20-16.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/3578232491_2026-01-18_19-27.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/374697721_2026-01-18_19-53.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/3973593677_2026-01-18_20-20.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/4109495794_2026-01-18_19-47.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/4145331905_2026-01-18_19-31.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/548762561_2026-01-18_19-57.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_180126/714335163_2026-01-18_19-51.pkl

Loaded 15 files from results/study_vdp/pyomo_network_size/pyomo_ho_32_180126
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/136325233_2026-01-19_04-06.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/1767054247_2026-01-19_04-32.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/1836724227_2026-01-19_04-14.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/1945847224_2026-01-19_03-30.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/225537992_2026-01-19_04-17.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/2445916811_2026-01-19_03-33.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/2802795955_2026-01-19_04-27.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/3434071976_2026-01-19_03-56.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/3757407551_2026-01-19_04-04.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/3815750524_2026-01-19_04-00.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/3834034679_2026-01-19_03-35.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/4026000142_2026-01-19_03-46.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/4187494663_2026-01-19_03-50.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/95307999_2026-01-19_03-52.pkl
Loaded results/study_vdp/pyomo_network_size/pyomo_ho_32_190126/956544185_2026-01-19_04-22.pkl

Loaded 15 files from results/study_vdp/pyomo_network_size/pyomo_ho_32_190126

In [7]:
results_reg_norm_df.head()

,system,reg,tol,time_elapsed,direct_model_pred,odeint_pred,odeint_pred_test,mse_train,mse_test,mse_train_coll,mse_test_coll,termination,seed
0,"(2, 4, 2)",0.1,1.000000e-08,6.368145,"[[0.0, 0.0007895340476428855, 0.00415965427098...","[[0.0, 1.0], [0.00078953407, 0.9999278], [0.00...","[[-0.0051915944, -0.99997276], [-0.00850154, -...",0.005370,0.033772,0.005256,0.038025,optimal,1181949418
1,"(2, 8, 2)",0.1,1.000000e-08,3.090557,"[[0.0, 0.0008314564442214137, 0.00438041222443...","[[0.0, 1.0], [0.00083145645, 0.9999422], [0.00...","[[-0.0051915944, -0.99997276], [-0.008599585, ...",0.004164,0.010113,0.004232,0.011426,optimal,1181949418
2,"(2, 16, 2)",0.1,1.000000e-08,28.955280,"[[-7.453727712678462e-20, 0.000342462157144158...","[[0.0, 1.0], [0.00034246215, 0.999804], [0.001...","[[-0.0051915944, -0.99997276], [-0.0046582287,...",0.690104,1336.641235,0.252842,3.194801,optimal,1181949418
3,"(2, 32, 2)",0.1,1.000000e-08,8.947290,"[[0.0, 0.0008636592108784206, 0.00454996409734...","[[0.0, 1.0], [0.0008636592, 0.99995726], [0.00...","[[-0.0051915944, -0.99997276], [-0.008669188, ...",0.003899,0.006376,0.004036,0.006897,optimal,1181949418
4,"(2, 64, 2)",0.1,1.000000e-08,6.180517,"[[4.980564570504495e-22, 0.0008695254482695389...","[[0.0, 1.0], [0.0008695254, 0.99996006], [0.00...","[[-0.0051915944, -0.99997276], [-0.008683949, ...",0.003943,0.006331,0.004061,0.006737,optimal,1181949418

In [13]:
results_reg_norm_df.groupby("system")[["time_elapsed", "mse_train_coll", "mse_test_coll"]].mean()

            time_elapsed  mse_train_coll  mse_test_coll
system
(2, 4, 2)       4.036635        0.265108       0.293028
(2, 8, 2)      14.614784        0.160729       0.161008
(2, 16, 2)     14.777241        0.144499       0.393528
(2, 32, 2)     52.818268        0.003780       0.006506
(2, 64, 2)     10.263043        0.027654       0.036012
(2, 96, 2)     69.293898        0.075357       0.095222

In [17]:
results_no_reg_norm_df

,system,reg,tol,time_elapsed,direct_model_pred,odeint_pred,odeint_pred_test,mse_train,mse_test,mse_train_coll,mse_test_coll,termination,seed
0,"(2, 4, 2)",0.1,1.000000e-08,1.412954,"[[0.0, 0.0007895340461277254, 0.00415965426301...","[[0.0, 1.0], [0.00078953407, 0.9999278], [0.00...","[[-0.0051915944, -0.99997276], [-0.00850154, -...",0.005370,0.033772,0.005256,0.038025,optimal,136325233
1,"(2, 8, 2)",0.1,1.000000e-08,3.681846,"[[0.0, 0.0008314564441929631, 0.00438041222428...","[[0.0, 1.0], [0.00083145645, 0.9999422], [0.00...","[[-0.0051915944, -0.99997276], [-0.008599585, ...",0.004164,0.010113,0.004232,0.011426,optimal,136325233
2,"(2, 16, 2)",0.1,1.000000e-08,8.250884,"[[0.0, 0.0008527035918476933, 0.00449228408461...","[[0.0, 1.0], [0.0008527036, 0.9999519], [0.004...","[[-0.0051915944, -0.99997276], [-0.00864439, -...",0.003950,0.007061,0.004038,0.007613,optimal,136325233
3,"(2, 32, 2)",0.1,1.000000e-08,4.796274,"[[0.0, 0.0008636590284274753, 0.00454996322716...","[[0.0, 1.0], [0.000863659, 0.99995726], [0.004...","[[-0.0051915944, -0.99997276], [-0.008669189, ...",0.003899,0.006376,0.004036,0.006897,optimal,136325233
4,"(2, 64, 2)",0.1,1.000000e-08,7.758429,"[[-4.857751131428936e-21, 0.000869525437093437...","[[0.0, 1.0], [0.0008695254, 0.99996006], [0.00...","[[-0.0051915944, -0.99997276], [-0.008683949, ...",0.003943,0.006331,0.004061,0.006737,optimal,136325233
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,"(2, 8, 2)",0.1,1.000000e-08,1.890598,"[[0.0, 0.000831456448561737, 0.004380412247311...","[[0.0, 1.0], [0.00083145645, 0.9999422], [0.00...","[[-0.0051915944, -0.99997276], [-0.008599585, ...",0.004164,0.010113,0.004232,0.011426,optimal,956544185
2,"(2, 16, 2)",0.1,1.000000e-08,188.845995,"[[0.0, 0.0008527035873888067, 0.00449228406103...","[[0.0, 1.0], [0.0008527036, 0.9999519], [0.004...","[[-0.0051915944, -0.99997276], [-0.00864439, -...",0.003950,0.007061,0.004038,0.007613,optimal,956544185
3,"(2, 32, 2)",0.1,1.000000e-08,6.216106,"[[0.0, -8.354845939126799e-06, -4.397417228106...","[[0.0, 1.0], [-8.354846e-06, 0.99969363], [-4....","[[-0.0051915944, -0.99997276], [-0.0051202034,...",0.361829,0.450540,0.361830,0.450548,optimal,956544185
4,"(2, 64, 2)",0.1,1.000000e-08,5.970064,"[[1.1188395083176781e-20, 0.000869525446403070...","[[0.0, 1.0], [0.0008695254, 0.99996006], [0.00...","[[-0.0051915944, -0.99997276], [-0.008683949, ...",0.003943,0.006331,0.004061,0.006737,optimal,956544185
5,"(2, 96, 2)",0.1,1.000000e-08,10.498558,"[[0.0, 0.0008714648281753698, 0.00459105809062...","[[0.0, 1.0], [0.00087146484, 0.999961], [0.004...","[[-0.0051915944, -0.99997276], [-0.008688921, ...",0.003961,0.006351,0.004073,0.006707,optimal,956544185

In [16]:
results_no_reg_norm_df.groupby("system")[["time_elapsed", "mse_train_coll", "mse_test_coll"]].mean()

            time_elapsed  mse_train_coll  mse_test_coll
system
(2, 4, 2)       3.819714        0.070303       0.126268
(2, 8, 2)      28.645436        0.028089       0.040762
(2, 16, 2)     30.892113        0.004038       0.007613
(2, 32, 2)     51.439840        0.075595       0.095627
(2, 64, 2)     56.132313        0.027909       0.036314
(2, 96, 2)     13.734692        0.075612       0.095435